# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(797, 606)
        self.table = QtWidgets.QTableWidget(Dialog)
        self.table.setGeometry(QtCore.QRect(10, 90, 591, 171))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 270, 781, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.plotLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.plotLayout.setContentsMargins(0, 0, 0, 0)
        self.plotLayout.setObjectName("plotLayout")
        self.box_wavelength = QtWidgets.QDoubleSpinBox(Dialog)
        self.box_wavelength.setGeometry(QtCore.QRect(120, 0, 91, 31))
        self.box_wavelength.setMinimum(100.0)
        self.box_wavelength.setMaximum(10000.0)
        self.box_wavelength.setProperty("value", 1600.0)
        self.box_wavelength.setObjectName("box_wavelength")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(7, 4, 111, 20))
        self.label.setObjectName("label")
        self.box_compQ = QtWidgets.QLineEdit(Dialog)
        self.box_compQ.setGeometry(QtCore.QRect(360, 0, 221, 31))
        self.box_compQ.setObjectName("box_compQ")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(280, 4, 71, 20))
        self.label_2.setObjectName("label_2")
        self.box_range1 = QtWidgets.QDoubleSpinBox(Dialog)
        self.box_range1.setGeometry(QtCore.QRect(120, 50, 91, 31))
        self.box_range1.setMinimum(-9999.0)
        self.box_range1.setMaximum(9999.99)
        self.box_range1.setObjectName("box_range1")
        self.box_range2 = QtWidgets.QDoubleSpinBox(Dialog)
        self.box_range2.setGeometry(QtCore.QRect(240, 50, 91, 31))
        self.box_range2.setMinimum(-9999999.0)
        self.box_range2.setMaximum(9999999.0)
        self.box_range2.setProperty("value", 4500.0)
        self.box_range2.setObjectName("box_range2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 55, 61, 20))
        self.label_3.setObjectName("label_3")
        self.box_plotNumPoints = QtWidgets.QSpinBox(Dialog)
        self.box_plotNumPoints.setGeometry(QtCore.QRect(410, 50, 81, 31))
        self.box_plotNumPoints.setMinimum(100)
        self.box_plotNumPoints.setMaximum(99999)
        self.box_plotNumPoints.setProperty("value", 1000)
        self.box_plotNumPoints.setObjectName("box_plotNumPoints")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(390, 56, 21, 20))
        self.label_4.setObjectName("label_4")
        self.button_rowAddA = QtWidgets.QPushButton(Dialog)
        self.button_rowAddA.setGeometry(QtCore.QRect(610, 140, 121, 25))
        self.button_rowAddA.setObjectName("button_rowAddA")
        self.button_rowDel = QtWidgets.QPushButton(Dialog)
        self.button_rowDel.setGeometry(QtCore.QRect(610, 220, 121, 25))
        self.button_rowDel.setObjectName("button_rowDel")
        self.button_save = QtWidgets.QPushButton(Dialog)
        self.button_save.setGeometry(QtCore.QRect(740, 10, 51, 41))
        self.button_save.setObjectName("button_save")
        self.button_load = QtWidgets.QPushButton(Dialog)
        self.button_load.setGeometry(QtCore.QRect(740, 60, 51, 41))
        self.button_load.setObjectName("button_load")
        self.button_rowAddB = QtWidgets.QPushButton(Dialog)
        self.button_rowAddB.setGeometry(QtCore.QRect(610, 170, 121, 25))
        self.button_rowAddB.setObjectName("button_rowAddB")
        self.button_replot = QtWidgets.QPushButton(Dialog)
        self.button_replot.setGeometry(QtCore.QRect(530, 50, 71, 31))
        self.button_replot.setObjectName("button_replot")
        self.button_export = QtWidgets.QPushButton(Dialog)
        self.button_export.setGeometry(QtCore.QRect(668, 300, 111, 25))
        self.button_export.setObjectName("button_export")
        self.checkBox_grid = QtWidgets.QCheckBox(Dialog)
        self.checkBox_grid.setGeometry(QtCore.QRect(580, 300, 61, 23))
        self.checkBox_grid.setObjectName("checkBox_grid")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Wavelength (nm)"))
        self.box_compQ.setText(_translate("Dialog", "333.891508583+86.8643618952j"))
        self.label_2.setText(_translate("Dialog", "Complex q"))
        self.label_3.setText(_translate("Dialog", "Plot Range"))
        self.label_4.setText(_translate("Dialog", "N"))
        self.button_rowAddA.setText(_translate("Dialog", "Add Row Above"))
        self.button_rowDel.setText(_translate("Dialog", "Del Row"))
        self.button_save.setText(_translate("Dialog", "Save"))
        self.button_load.setText(_translate("Dialog", "Load"))
        self.button_rowAddB.setText(_translate("Dialog", "Add Row Below"))
        self.button_replot.setText(_translate("Dialog", "Replot"))
        self.button_export.setText(_translate("Dialog", "Export Result"))
        self.checkBox_grid.setText(_translate("Dialog", "Grid"))

